#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# event nethserver-ha-update
#

event_actions('nethserver-ha-update', qw(
    initialize-default-databases 00
));

event_templates('nethserver-ha-update', qw(
    /etc/hosts
));

#
# event nethserver-ha-save
#
event_templates('nethserver-ha-save', qw(
    /etc/sysconfig/cman
    /etc/hosts
    /etc/drbd.d/drbd00.res
));

event_actions('nethserver-ha-save', qw(
    nethserver-ha-createcluster 20
    nethserver-ha-drbd 30
    nethserver-ha-pcsd 40
));

#
# event password-modify
# generate a new secret when root's password changes
#

event_actions('password-modify', qw(
    nethserver-ha-syncpcspw 40
));

