#!/usr/bin/perl -w

use strict;
use esmith::Build::CreateLinks qw(:all);

my $event = 'nethserver-ha-update';

event_templates($event, qw(
    /etc/sysconfig/cman
));

event_actions($event, qw(
    nethserver-ha-conf 50
));

event_actions('password-modify', qw(
    nethserver-ha-syncpcspw 40
));

