#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

#
# set hacluster's password as a one-way hash of root's one
#

if ! [ $# -ge 3 ]; then
   echo "[ERROR] Not enough arguments."
   exit 2
fi

EVENT=$1
USER=$2
FILE=$3

if [[ $USER != "root" ]]; then
    # nothing to do
    exit 0
fi

if ! [[ -f "${FILE}" ]]; then
    echo "[ERROR] Password file not found"
    exit 1
fi

PASSWORD=NS7.`(cat $FILE; echo -n ns7) | sha1sum | cut -d ' ' -f 1`
echo -e "$PASSWORD\n$PASSWORD" | /usr/bin/passwd --stdin hacluster

umask 077
echo -n "$PASSWORD" > /var/lib/nethserver/secrets/hacluster

