#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

if  ! service pcsd status &>/dev/null then
    service pcsd start
fi

PASSWORD=$(perl -MNethServer::Password -e 'print NethServer::Password::store("hacluster");')
pcs cluster auth --local --force -u hacluster -p "${PASSWORD:-Nethesis,1234}"

if ! pcs cluster status &>/dev/null; then
    pcs cluster start $(hostname)
fi