#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use NethServer::Service;
use esmith::ConfigDB;

my $cdb = esmith::ConfigDB->open_ro() || die("Could not open ConfigDB");

my $pcsd = NethServer::Service->new('pcsd');

# If cluster is configured exit now:
if($pcsd->is_running()) {
    exit(0);
}

foreach ($cdb->get_all_by_prop('type' => 'clustered')) {
    my $svc = NethServer::Service->new($_->key);
    $svc->stop();
    if( -e "/etc/rc.d/init.d/" . $_->key) {
        $svc->_set_sysv_startup(0);
    }
}

