#!/bin/bash

set -e

NODE1=nv1.nethserverha
NODE2=nv2.nethserverha
NODE1_IP=192.168.144.51
NODE2_IP=192.168.144.52

# Set hostnames
db hosts set $NODE1 remote IpAddress $NODE1_IP
db hosts set $NODE2 remote IpAddress $NODE2_IP
signal-event nethserver-hosts-update

# Configure corosync

ccs -f /etc/cluster/cluster.conf --createcluster nethserverha
ccs -f /etc/cluster/cluster.conf --addnode $NODE1
ccs -f /etc/cluster/cluster.conf --addnode $NODE2
ccs -f /etc/cluster/cluster.conf --addfencedev pcmk agent=fence_pcmk
ccs -f /etc/cluster/cluster.conf --addmethod pcmk-redirect $NODE1
ccs -f /etc/cluster/cluster.conf --addmethod pcmk-redirect $NODE2
ccs -f /etc/cluster/cluster.conf --addfenceinst pcmk $NODE1 pcmk-redirect port=$NODE1
ccs -f /etc/cluster/cluster.conf --addfenceinst pcmk $NODE1 pcmk-redirect port=$NODE2

# Generate password for pcs
password=`perl -e 'use NethServer::Directory; my $password = NethServer::Directory::getUserPassword("hacluster", 0) ; printf $password;'`

echo -e "$password\n$password" | passwd --stdin hacluster

pcs cluster auth -u hacluster -p "$password"
