#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

DOMAIN=$(hostname -d)
NODE1="ns1.${DOMAIN:-localdomain}"
NODE2="ns2.${DOMAIN:-localdomain}"
CONF="/etc/cluster/cluster.conf"

if [ -f $CONF ]; then
    echo "[INFO] Cluster already configured, skipping ccs commands"
    exit 0
fi

ccs -f ${CONF} --createcluster nethserverha
ccs -f ${CONF} --addnode ${NODE1}
ccs -f ${CONF} --addnode ${NODE2}
ccs -f ${CONF} --addfencedev pcmk agent=fence_pcmk
ccs -f ${CONF} --addmethod pcmk-redirect ${NODE1}
ccs -f ${CONF} --addmethod pcmk-redirect ${NODE2}
ccs -f ${CONF} --addfenceinst pcmk ${NODE1} pcmk-redirect port=${NODE1}
ccs -f ${CONF} --addfenceinst pcmk ${NODE2} pcmk-redirect port=${NODE2}

echo "[INFO] Configured ${CONF} with ${NODE1} and ${NODE2}"
