#!/bin/bash

set -e

NODE1=nv1.nethserverha
NODE2=nv2.nethserverha

# Set hostnames
db hosts set nv1.nethvoiceha remote IpAddress $NODE1
db hosts set nv2.nethvoiceha remote IpAddress $NODE2
signal-event nethserver-hosts-update

# Configure corosync

ccs -f /etc/cluster/cluster.conf --createcluster nethserverha
ccs -f /etc/cluster/cluster.conf --addnode $NODE1
ccs -f /etc/cluster/cluster.conf --addnode $NODE2
ccs -f /etc/cluster/cluster.conf --addfencedev pcmk agent=fence_pcmk
ccs -f /etc/cluster/cluster.conf --addmethod pcmk-redirect $NODE1
ccs -f /etc/cluster/cluster.conf --addmethod pcmk-redirect $NODE2
ccs -f /etc/cluster/cluster.conf --addfenceinst pcmk $NODE1 pcmk-redirect port=$NODE1
ccs -f /etc/cluster/cluster.conf --addfenceinst pcmk $NODE1 pcmk-redirect port=$NODE2

# Generate password for pcs
password=`perl -e 'use NethServer::Directory; my $password = NethServer::Directory::getUserPassword("hacluster", 0) ; printf $password;'`

echo -e "$password\n$password" | passwd --stdin hacluster

pcs cluster auth -u hacluster -p "$password"
