#!/bin/bash

RES=drbd00

disk=`config getprop ha DrbdDisk`
drbdadm down $RES &>/dev/null
dd if=/dev/zero of=$disk bs=1M count=1 &>/dev/null
echo yes | drbdadm wipe-md $RES &>/dev/null
drbdadm create-md $RES
drbdadm up $RES
drbdadm --force primary $RES
