#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

RES=drbd00

disk=`config getprop ha DrbdDisk`
if [ "x$disk" == "x" ]; then
    echo "No DrbdDisk configured"
    exit 1
fi

if blkid $disk -o value -s TYPE; then
    echo "Block device $disk is already configured!"
    echo
    echo "To wipe the device use the following commands:"
    echo "  dd if=/dev/zero of=$disk bs=1M count=1"
    echo "  drbdadm wipe-md $RES"
    exit 0
fi

drbdadm create-md $RES

system_name=`config get SystemName`
if [ "$system_name" == 'ns1' ]; then
    :
elif [ "$system_name" == 'ns2' ]; then
    exit 0
else
    echo "Invalid SystemName '$system_name'"
    exit 1
fi

virtual_ip=`config getprop ha VirtualIP`
if [ "x$virtual_ip" == "x" ]; then
    echo "Virtual IP not set"
    exit 1
fi

ping -q -W 1 -c 1 $virtual_ip >/dev/null
if [ $? -eq 0 ]; then
    echo "Virtual IP '$virtual_ip' is online: DRBD creation skipped"
    exit 0
fi

if read < /dev/tcp/ns2/7789 &>/dev/null; then
    echo "[INFO] Node ns2 is online: DRBD creation skipped"
    exit 0
fi

# Initialize the DRBD device
if ! findfs LABEL=drbd; then
   drbdadm up $RES
   drbdadm --force primary $RES
   mkfs.ext4 -L drbd /dev/drbd/by-res/$RES
   sync
   sleep 1
   drbdadm down $RES
fi

